### ISSUE TITLE
Allow importing multiple files with the same name

### ISSUE THREAD

**Issue by khepin** [servergrove/TranslationEditorBundle#2]
Right now all my translations are in files called "messages.locale.yml". The bundle will then only import one file since the indexes are created based only on the filename. It should be feasible to add the bundle name in there as well to ensure that there is no name crash.

**Comment by pgodel** [comment]
Adding the bundle name is a good idea.

**Comment by khepin** [comment]
Same thing, giving it a shot. My mongo experience is a 3 minutes one so far though!

**Comment by khepin** [comment]
My bad, the filename saved is the whole path, so there's no name crash inside the DB. It seems that it happens when sorting on the locale in the listAction controller.

**Comment by iambrosi** [comment]
This has been fixed
