### ISSUE TITLE
Importing whole folder gets lost

### ISSUE THREAD

**Issue by rdohms** [servergrove/TranslationEditorBundle#3]
I trie importing from the FOSUserBundle which has 2 files in multiple locales: i.e FOSUserBundle.en.yml, FOSUserBundle.nl.yml.. and validators.en.yml, validators.nl.yml

When i do the import it finds all these files, but when i access the editor it only shows the last file contents, all languages, but only for this filename.

Is this an issue or am i using it wrong?

**Comment by khepin** [comment]
Yep this is actually the same issue as #2, I'm trying to work on a different way to do this. For now you can only get one file at a time.

**Comment by servergrove** [comment]
@rdohms this issue was fixed by https://github.com/servergrove/TranslationEditorBundle/issues/2
